Repository spe-uob/2021-ARReshare, pull requests merged in 2022-05, with the labels that each got.

#175 Change product activity to fragment and sync bookmark functionality with feed
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ar_reshare/ARActivity.java
  app/src/main/java/com/example/ar_reshare/FeedActivity.java
  app/src/main/java/com/example/ar_reshare/FeedRecyclerAdapter.java
  app/src/main/java/com/example/ar_reshare/MapsActivity.java
  app/src/main/java/com/example/ar_reshare/ProductPageActivity.java
  app/src/main/java/com/example/ar_reshare/SwipeActivity.java
  app/src/main/res/layout/activity_product_page.xml
  app/src/main/res/layout/activity_swipe.xml
Labels: enhancement

#176 Changes of navijgation bar to develop
  app/src/main/java/com/example/ar_reshare/ChatListActivity.java
  app/src/main/java/com/example/ar_reshare/MultiChatsAdapter.java
  app/src/main/java/com/example/ar_reshare/SwipeActivity.java
  app/src/main/res/drawable/navigation_color.xml
  app/src/main/res/layout/activity_chat_list.xml
  app/src/main/res/layout/activity_feed.xml
  app/src/main/res/layout/activity_swipe.xml
  app/src/main/res/menu/bottom_nav_menu.xml
Labels: enhancement

#179 Feed Visual Update Inline With Agreed Design Scheme
  app/src/main/java/com/example/ar_reshare/FeedRecyclerAdapter.java
  app/src/main/java/com/example/ar_reshare/ProductPageActivity.java
  app/src/main/res/drawable/add_icon.xml
  app/src/main/res/drawable/black_bookmark.xml
  app/src/main/res/drawable/custom_border.xml
  app/src/main/res/drawable/feed_filter_icon.xml
  app/src/main/res/drawable/feed_text_border.xml
  app/src/main/res/drawable/filled_black_bookmark.xml
  app/src/main/res/drawable/ic_baseline_message_24.xml
  app/src/main/res/drawable/ic_baseline_question_mark_24.xml
  app/src/main/res/drawable/location_pin.xml
  app/src/main/res/drawable/refresh_icon.xml
  app/src/main/res/layout/activity_feed.xml
  app/src/main/res/layout/item_view.xml
Labels: enhancement

#180 Stabilise, Add Instructions, Prevent Crashing and Improve Accuracy of AR
  app/src/main/AndroidManifest.xml
  app/src/main/assets/models/accessory_colours.png
  app/src/main/assets/models/books_colours.png
  app/src/main/assets/models/clothing_colours.png
  app/src/main/assets/models/electronics_colours.png
  app/src/main/assets/models/household_colours.png
  app/src/main/assets/models/others_colours.png
  app/src/main/java/com/example/ar_reshare/ARActivity.java
  app/src/main/java/com/example/ar_reshare/Compass.java
  app/src/main/res/drawable-v24/justin_beaver.jpg
  app/src/main/res/drawable/compass_graphic.png
  app/src/main/res/drawable/information_icon.xml
  app/src/main/res/layout/activity_aractivity.xml
  app/src/main/res/layout/ar_product_box.xml
  app/src/main/res/layout/instructions_popup.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#184 Navigation fix
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ar_reshare/AddProduct.java
  app/src/main/java/com/example/ar_reshare/FeedRecyclerAdapter.java
  app/src/main/java/com/example/ar_reshare/ModifyProduct.java
  app/src/main/java/com/example/ar_reshare/ProductPageActivity.java
  app/src/main/java/com/example/ar_reshare/SwipeActivity.java
Labels: enhancement

#185 fixed modify image bug
  app/src/main/java/com/example/ar_reshare/ProductPageActivity.java
Labels: enhancement

#186 Increase the Speed and Accuracy of AR and Fix All Related Bugs
  app/src/main/java/com/example/ar_reshare/ARActivity.java
  app/src/main/java/com/example/ar_reshare/FeedActivity.java
  app/src/main/java/com/example/ar_reshare/MapsActivity.java
  app/src/main/java/com/example/ar_reshare/ProductPageActivity.java
  app/src/main/java/com/example/ar_reshare/ProfileActivity.java
  app/src/main/res/layout/single_filter_chip.xml
Labels: bug, enhancement

#193 Implement Close Account and Cosmetic Changes to Settings
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ar_reshare/BackendController.java
  app/src/main/java/com/example/ar_reshare/BackendService.java
  app/src/main/java/com/example/ar_reshare/PostcodeDetails.java
  app/src/main/java/com/example/ar_reshare/PostcodeHelper.java
  app/src/main/java/com/example/ar_reshare/ProfileActivity.java
  app/src/main/java/com/example/ar_reshare/SettingsActivity.java
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/delete_account_dialog.xml
  app/src/main/res/layout/email_dialog.xml
  app/src/main/res/layout/fullname_dialog.xml
  app/src/main/res/layout/homeaddress_dialog.xml
  app/src/main/res/layout/pwd_dialog.xml
  docs/ar-reshare-backend.png
  docs/ar-reshare_models.png
  docs/ar-reshare_ui.png
Labels: enhancement

#195 Fix Bug in Message
  app/src/main/java/com/example/ar_reshare/ChatListActivity.java
  app/src/main/java/com/example/ar_reshare/MessageListAdapter.java
  app/src/main/java/com/example/ar_reshare/MessagingActivity.java
  app/src/main/java/com/example/ar_reshare/MultiChatsAdapter.java
  app/src/main/res/layout/activity_chat_list.xml
  app/src/main/res/layout/message_chat_layout.xml
Labels: bug

#197 Message bug fix
  app/src/main/java/com/example/ar_reshare/MessagingActivity.java
  app/src/main/java/com/example/ar_reshare/MultiChatsAdapter.java
Labels: bug
